apiVersion: apps/v1 
kind: Deployment #type of the resource
metadata:
  name: react-frontend1 #name of the deployment
spec:
  replicas: 2 #number of pod replicas
  selector:
    matchLabels:
      app: react-frontend1 #label to identify the pods
  template:
    metadata:
      labels:
        app: react-frontend1 #label for the pods
    spec:
      containers:
        - name: react #name of the container
          image: jayanth007/react-frontend-1:latest #docker image to be used for the containerr
          imagePullPolicy: Always
          ports:
            - containerPort: 80   #this is the port on which the container will listen for incoming traffic(which is nginx actually listening on)