apiVersion: v1
kind: Service #type of the resource
metadata:
  name: react-service #name of the service
spec:
  type: NodePort #type of the service
  selector:
    app: react-frontend1 #label to identify the pods
  ports:
    - port: 80 #port on which the service will be exposed
      targetPort: 80 #port on which the container is listening(which is nginx actually listening on)
      nodePort: 30080 #port on which the service will be accessible on the node

# Browser
#   ↓ 30007 #node's port
# Node (NodePort)
#   ↓ 80 #service is listening here
# Service
#   ↓ 80
# Pod       #pods are listening here(which is nginx actually listening on)
#   ↓ 80
# Nginx
#   ↓
# React app